name: Update tutors.json
run-name: ${{ github.actor }} is updating tutors.json 🚀
on: [workflow_dispatch]
jobs:
  Update-Tutors:
    runs-on: ubuntu-latest
    env: 
      BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
      GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      CLOUDINARY_KEY: ${{ secrets.CLOUDINARY_KEY }}
      TUTORS_GOOGLE_SHEET_ID: ${{ vars.TUTORS_GOOGLE_SHEET_ID }}
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install urllib3 cloudinary google-api-python-client google-auth gspread
      - name: Run code
        run: |
          python3 update_tutors_json.py
          
